import { FilterCategory } from "../types/Category";

export const categories: FilterCategory[] = [
  {
    id: "brand",
    name: "brand",
    items: [
      { name: "Astrophil Stella", isChecked: false },
      { name: "Attar Collection", isChecked: false },
      { name: "Azzaro", isChecked: false },
      { name: "Dame Perfumery", isChecked: false },
      { name: "Diptyque", isChecked: false },
      { name: "Elizabeth Arden", isChecked: false },
      { name: "Escentric Molecules", isChecked: false },
      { name: "Giorgio Armani", isChecked: false },
      { name: "Hugo Boss", isChecked: false },
      { name: "Jean Paul Gaultier", isChecked: false },
      { name: "Maison Matine", isChecked: false },
      { name: "Narciso Rodriguez", isChecked: false },
      { name: "Paco Rabanne", isChecked: false },
      { name: "Parfums MDCI", isChecked: false },
      { name: "Salvatore Ferragamo", isChecked: false },
      { name: "Strangers Parfumerie", isChecked: false },
      { name: "Thierry Mugler", isChecked: false },
      { name: "Amouage", isChecked: false },
      { name: "Armaf", isChecked: false },
      { name: "Burberry", isChecked: false },
      { name: "By Kilian", isChecked: false },
      { name: "Byredo", isChecked: false },
      { name: "Creed", isChecked: false },
      { name: "Diesel", isChecked: false },
      { name: "Hermès", isChecked: false },
      { name: "Imaginary Authors", isChecked: false },
      { name: "Jo Malone", isChecked: false },
      { name: "KENZO", isChecked: false },
      { name: "L'Occitane en Provence", isChecked: false },
      { name: "Label", isChecked: false },
      { name: "Le Labo", isChecked: false },
      { name: "Maison Margiela", isChecked: false },
      { name: "Marie Jeanne", isChecked: false },
      { name: "Masque Milano", isChecked: false },
      { name: "MCM", isChecked: false },
      { name: "Moschino", isChecked: false },
      { name: "Nishane", isChecked: false },
      { name: "Prada", isChecked: false },
      { name: "Tom Ford", isChecked: false },
      { name: "Valentino", isChecked: false },
      { name: "Afnan", isChecked: false },
      { name: "Al Haramain", isChecked: false },
      { name: "Bvlgari", isChecked: false },
      { name: "Carolina Herrera", isChecked: false },
      { name: "D&G", isChecked: false },
      { name: "Dasein", isChecked: false },
      { name: "Dior", isChecked: false },
      { name: "ELDO", isChecked: false },
      { name: "Ex Nihilo", isChecked: false },
      { name: "Fragments by NV", isChecked: false },
      { name: "Givenchy", isChecked: false },
      { name: "Guerlain", isChecked: false },
      { name: "Initio Parfums Prives", isChecked: false },
      { name: "Issey Miyake", isChecked: false },
      { name: "L'Orchestre Parfum", isChecked: false },
      { name: "Marc Antoine Barrois", isChecked: false },
      { name: "Marc Jacobs", isChecked: false },
      { name: "Memo Paris", isChecked: false },
      { name: "Montblanc", isChecked: false },
      { name: "Nautica", isChecked: false },
      { name: "Rochas", isChecked: false },
      { name: "Roja Parfum", isChecked: false },
      { name: "Xerjoff", isChecked: false },
      { name: "Yves Saint Laurent", isChecked: false },
      { name: "Zoologist", isChecked: false },
      { name: "Acqua di Parma", isChecked: false },
      { name: "Art de Parfum", isChecked: false },
      { name: "Calvin Klein", isChecked: false },
      { name: "Carner Barcelona", isChecked: false },
      { name: "Chanel", isChecked: false },
      { name: "Chloé", isChecked: false },
      { name: "Clive Christian", isChecked: false },
      { name: "Gucci", isChecked: false },
      { name: "Lalique", isChecked: false },
      { name: "Lancôme", isChecked: false },
      { name: "Maison Francis Kurkdjian", isChecked: false },
      { name: "Mancera", isChecked: false },
      { name: "Nasomatto", isChecked: false },
      { name: "Optico", isChecked: false },
      { name: "Ormonde Jayne", isChecked: false },
      { name: "Orto Parisi", isChecked: false },
      { name: "Parfums de Marly", isChecked: false },
      { name: "Profvmvm Roma", isChecked: false },
      { name: "Versace", isChecked: false },
      { name: "Viktor & Rolf", isChecked: false },
    ],
    showMore: true,
  },
  {
    id: "gender",
    name: "gender",
    items: [
      { name: "Male", isChecked: false },
      { name: "Female", isChecked: false },
      { name: "Unisex", isChecked: false },
    ],
    showMore: false,
  },
  {
    id: "season",
    name: "season",
    items: [
      { name: "Spring", isChecked: false },
      { name: "Summer", isChecked: false },
      { name: "Autumn", isChecked: false },
      { name: "Winter", isChecked: false },
    ],
    showMore: false,
  },
  {
    id: "price",
    name: "price",
    items: [
      { name: "20-50", isChecked: false },
      { name: "50-100", isChecked: false },
      { name: "100-250", isChecked: false },
      { name: "250-500", isChecked: false },
      { name: "500-999999", isChecked: false },
    ],
    showMore: false,
  },
];
